# Generated by Django 5.2.8 on 2025-12-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_company_name_chatmessage_chatattachment_chatroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
