# Generated by Django 5.2.8 on 2026-07-02 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_resumeanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('overall_score', models.PositiveSmallIntegerField(default=0)),
                ('ats_score', models.PositiveSmallIntegerField(default=0)),
                ('readiness_score', models.PositiveSmallIntegerField(default=0)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume_analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_analysis', to='jobs.resumeanalysis')),
            ],
            options={
                'verbose_name_plural': 'Career analyses',
            },
        ),
    ]
