# Generated by Django 5.2.8 on 2026-07-03 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_candidateembedding_jobembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecommendationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_jobs_considered', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_embedding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_runs', to='jobs.candidateembedding')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_runs', to='jobs.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('final_score', models.PositiveSmallIntegerField(default=0)),
                ('semantic_score', models.PositiveSmallIntegerField(default=0)),
                ('skills_score', models.PositiveSmallIntegerField(default=0)),
                ('readiness_score', models.PositiveSmallIntegerField(default=0)),
                ('ats_score', models.PositiveSmallIntegerField(default=0)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('explanation_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='jobs.job')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to='jobs.userprofile')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='jobs.jobrecommendationrun')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='jobrecommendationrun',
            index=models.Index(fields=['user_profile', '-created_at'], name='jobs_jobrec_user_pr_74cfcc_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendationrun',
            index=models.Index(fields=['status'], name='jobs_jobrec_status_c04945_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['user_profile', 'rank'], name='jobs_jobrec_user_pr_096bde_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['run', 'rank'], name='jobs_jobrec_run_id_4bba7e_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrecommendation',
            index=models.Index(fields=['job'], name='jobs_jobrec_job_id_1609dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobrecommendation',
            constraint=models.UniqueConstraint(fields=('run', 'job'), name='unique_recommendation_per_run_job'),
        ),
    ]
