# Generated by Django 5.2.8 on 2026-07-09 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_jobrecommendationrun_jobrecommendation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interview',
            constraint=models.UniqueConstraint(fields=('application',), name='unique_interview_per_application'),
        ),
    ]
